### ISSUE TITLE
[Feature] Reverse operation

### ISSUE THREAD

**Issue by pidgeon777** [xorid/asciitree.nvim#5]
Once a tree has been created, it would be nice to have a function which transforms it back to the original format.

**Comment by riddlew** [comment]
This has just been added a few hours ago in #2 (readme has not been updated to reflect it yet). `:AsciiTreeUndo` will convert a tree back to original text based on your settings. Currently if the tree was created with settings different than your settings (such as converting a tree with a branch depth of 8 when your settings are set to 2), you will need to specify it in the args when undoing it (same args as when converting text to tree, I plan to eliminate the need to do this in the future).
